name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api: [class]

    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run static site generation
        run: npm run build
